language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t techxorcist/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true techxorcist/docker-react npm run test -- --coverage
 
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-west-2-939684087678"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY